In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
# baseline in performance with logistic regression model
from sklearn.datasets import make_classification
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics.classification import accuracy_score, log_loss
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
##https://machinelearningmastery.com/autoencoder-for-classification/
# train autoencoder for classification with no compression in the bottleneck layer
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.utils import plot_model
from matplotlib import pyplot
from keras.models import load_model 
from imblearn.combine import SMOTEENN
from sklearn.metrics import classification_report
from sklearn import metrics

In [2]:
data=pd.read_csv("E:/Venu/Applied ai course/Assignments data and ipynb/Case study 1/tel_churn.csv")
data.head()

Unnamed: 0  SeniorCitizen  MonthlyCharges  TotalCharges  Churn  \
0           0              0           29.85         29.85      0   
1           1              0           56.95       1889.50      0   
2           2              0           53.85        108.15      1   
3           3              0           42.30       1840.75      0   
4           4              0           70.70        151.65      1   

   gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  ...  \
0              1            0           0            1              1  ...   
1              0            1           1            0              1  ...   
2              0            1           1            0              1  ...   
3              0            1           1            0              1  ...   
4              1            0           1            0              1  ...   

   PaymentMethod_Bank transfer (automatic)  \
0                                        0   
1                                        0   
2                                        0   
3                                        1   
4                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  mnth_tenure_group2_1 - 12  \
0                           0                          1   
1                           1                          0   
2                           1                          1   
3                           0                          0   
4                           0                          1   

   mnth_tenure_group2_13 - 24  mnth_tenure_group2_25 - 36  \
0                           0                           0   
1                           0                           1   
2                           0                           0   
3                           0                           0   
4                           0                           0   

   mnth_tenure_group2_37 - 48  mnth_tenure_group2_49 - 60  \
0                           0                           0   
1                           0                           0   
2                           0                           0   
3                           1                           0   
4                           0                           0   

   mnth_tenure_group2_61 - 72  
0                           0  
1                           0  
2                           0  
3                           0  
4                           0  

[5 rows x 52 columns]

In [3]:
data.shape

(7032, 52)

In [4]:
data=data.drop('Unnamed: 0',axis=1)

In [5]:
# Here dropping target variable for splitting input and output data for applying model
input=data.drop('Churn',axis=1)
input.head()

SeniorCitizen  MonthlyCharges  TotalCharges  gender_Female  gender_Male  \
0              0           29.85         29.85              1            0   
1              0           56.95       1889.50              0            1   
2              0           53.85        108.15              0            1   
3              0           42.30       1840.75              0            1   
4              0           70.70        151.65              1            0   

   Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  PhoneService_No  \
0           0            1              1               0                1   
1           1            0              1               0                0   
2           1            0              1               0                0   
3           1            0              1               0                1   
4           1            0              1               0                0   

   ...  PaymentMethod_Bank transfer (automatic)  \
0  ...                                        0   
1  ...                                        0   
2  ...                                        0   
3  ...                                        1   
4  ...                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  mnth_tenure_group2_1 - 12  \
0                           0                          1   
1                           1                          0   
2                           1                          1   
3                           0                          0   
4                           0                          1   

   mnth_tenure_group2_13 - 24  mnth_tenure_group2_25 - 36  \
0                           0                           0   
1                           0                           1   
2                           0                           0   
3                           0                           0   
4                           0                           0   

   mnth_tenure_group2_37 - 48  mnth_tenure_group2_49 - 60  \
0                           0                           0   
1                           0                           0   
2                           0                           0   
3                           1                           0   
4                           0                           0   

   mnth_tenure_group2_61 - 72  
0                           0  
1                           0  
2                           0  
3                           0  
4                           0  

[5 rows x 50 columns]

In [6]:
target=data['Churn']
target.shape

(7032,)

# Applying models without autoencoders

In [7]:
x_train1,x_test,y_train1,y_test=train_test_split(input, target,test_size=0.2)

In [8]:
print(x_train1.shape)
print(x_test.shape)
print(y_train1.shape)
print(y_test.shape)

(5625, 50)
(1407, 50)
(5625,)
(1407,)


In [9]:
sm = SMOTEENN()
x_train, y_train = sm.fit_sample(x_train1,y_train1)

In [10]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(4654, 50)
(1407, 50)
(4654,)
(1407,)


### #Logistic Regression with SGD Classifier

In [11]:
model_lg = SGDClassifier(alpha=0.001,loss='log',penalty='l2',random_state=24)
model_lg.fit(x_train,y_train)

SGDClassifier(alpha=0.001, loss='log', random_state=24)

In [12]:
y_predict = model_lg.predict(x_test)
score = model_lg.score(x_test, y_test)
print(score)
print(metrics.classification_report(y_test, y_predict))

0.6076759061833689
              precision    recall  f1-score   support

           0       0.84      0.57      0.68      1015
           1       0.39      0.72      0.50       392

    accuracy                           0.61      1407
   macro avg       0.61      0.64      0.59      1407
weighted avg       0.71      0.61      0.63      1407



In [13]:
print(metrics.confusion_matrix(y_test, y_predict))

[[574 441]
 [111 281]]


In [14]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predict, average='macro')

0.589891223994086

### Desicion tree 

In [15]:
DT = DecisionTreeClassifier()
max_depth=[1,5,10,50]
min_samples_split=[5,10,100,500]
parameters = {'max_depth':max_depth,'min_samples_split':min_samples_split}
clf_dt = RandomizedSearchCV(DT, parameters, cv= 10,return_train_score=True,verbose=2)
clf_dt.fit(x_train, y_train)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
[CV] min_samples_split=5, max_depth=50 ...............................
[CV] ................ min_samples_split=5, max_depth=50, total=   0.1s
[CV] min_samples_split=5, max_depth=50 ...............................
[CV] ................ min_samples_split=5, max_depth=50, total=   0.1s
[CV] min_samples_split=5, max_depth=50 ...............................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] ................ min_samples_split=5, max_depth=50, total=   0.1s
[CV] min_samples_split=5, max_depth=50 ...............................
[CV] ................ min_samples_split=5, max_depth=50, total=   0.1s
[CV] min_samples_split=5, max_depth=50 ...............................
[CV] ................ min_samples_split=5, max_depth=50, total=   0.0s
[CV] min_samples_split=5, max_depth=50 ...............................
[CV] ................ min_samples_split=5, max_depth=50, total=   0.1s
[CV] min_samples_split=5, max_depth=50 ...............................
[CV] ................ min_samples_split=5, max_depth=50, total=   0.1s
[CV] min_samples_split=5, max_depth=50 ...............................
[CV] ................ min_samples_split=5, max_depth=50, total=   0.1s
[CV] min_samples_split=5, max_depth=50 ...............................
[CV] ................ min_samples_split=5, max_depth=50, total=   0.1s
[CV] min_samples_split=5, max_depth=50 ...............................
[CV] .

[CV] ............... min_samples_split=10, max_depth=50, total=   0.1s
[CV] min_samples_split=10, max_depth=50 ..............................
[CV] ............... min_samples_split=10, max_depth=50, total=   0.0s
[CV] min_samples_split=10, max_depth=50 ..............................
[CV] ............... min_samples_split=10, max_depth=50, total=   0.0s
[CV] min_samples_split=10, max_depth=50 ..............................
[CV] ............... min_samples_split=10, max_depth=50, total=   0.0s
[CV] min_samples_split=10, max_depth=50 ..............................
[CV] ............... min_samples_split=10, max_depth=50, total=   0.1s
[CV] min_samples_split=10, max_depth=50 ..............................
[CV] ............... min_samples_split=10, max_depth=50, total=   0.0s
[CV] min_samples_split=10, max_depth=50 ..............................
[CV] ............... min_samples_split=10, max_depth=50, total=   0.1s
[CV] min_samples_split=10, max_depth=50 ..............................
[CV] .

[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    4.8s finished


RandomizedSearchCV(cv=10, estimator=DecisionTreeClassifier(),
                   param_distributions={'max_depth': [1, 5, 10, 50],
                                        'min_samples_split': [5, 10, 100, 500]},
                   return_train_score=True, verbose=2)

In [16]:
print(clf_dt.best_estimator_)

DecisionTreeClassifier(max_depth=10, min_samples_split=5)


In [17]:
clf_best=DecisionTreeClassifier(max_depth=10, min_samples_split=10)
clf_best.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=10, min_samples_split=10)

In [18]:
y_predict_dt = clf_best.predict(x_test)
score_dt = clf_best.score(x_test, y_test)
print(score_dt)
print(metrics.classification_report(y_test, y_predict_dt))

0.7121535181236673
              precision    recall  f1-score   support

           0       0.85      0.73      0.79      1015
           1       0.49      0.67      0.56       392

    accuracy                           0.71      1407
   macro avg       0.67      0.70      0.67      1407
weighted avg       0.75      0.71      0.72      1407



In [19]:
print(metrics.confusion_matrix(y_test, y_predict_dt))

[[740 275]
 [130 262]]


In [20]:
f1_score(y_test, y_predict_dt, average='macro')

0.6745966256749079

### Random Forest

In [21]:
from scipy.stats import randint as sp_randint
param_dist = {'n_estimators':[100,200,500,1000,2000],
              'max_depth':[3,5,10],
              "min_samples_split": sp_randint(10,19),
              "min_samples_leaf": sp_randint(25,65)}

clf = RandomForestClassifier(random_state=25,n_jobs=-1)

rf_random = RandomizedSearchCV(clf, param_distributions=param_dist,
                                   n_iter=5,cv=5,random_state=25,return_train_score=True)

rf_random.fit(x_train,y_train)

RandomizedSearchCV(cv=5,
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=25),
                   n_iter=5,
                   param_distributions={'max_depth': [3, 5, 10],
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000015AF0336880>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000015AF0341E80>,
                                        'n_estimators': [100, 200, 500, 1000,
                                                         2000]},
                   random_state=25, return_train_score=True)

In [22]:
print(rf_random.best_estimator_)

RandomForestClassifier(max_depth=10, min_samples_leaf=33, min_samples_split=14,
                       n_estimators=200, n_jobs=-1, random_state=25)


In [23]:
clf = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=33, min_samples_split=14,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
            oob_score=False, random_state=25, verbose=0, warm_start=False)

In [24]:
clf.fit(x_train,y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=33, min_samples_split=14,
                       n_estimators=200, n_jobs=-1, random_state=25)

In [25]:
y_predict_rf = rf_random.predict(x_test)
score_rf = rf_random.score(x_test, y_test)
print(score_rf)
print(metrics.classification_report(y_test, y_predict_rf))

0.7263681592039801
              precision    recall  f1-score   support

           0       0.89      0.71      0.79      1015
           1       0.51      0.77      0.61       392

    accuracy                           0.73      1407
   macro avg       0.70      0.74      0.70      1407
weighted avg       0.78      0.73      0.74      1407



In [26]:
print(metrics.confusion_matrix(y_test, y_predict_rf))

[[719 296]
 [ 89 303]]


### XGBoost Classifier

In [27]:
# https://www.analyticsvidhya.com/blog/2016/03/complete-guide-parameter-tuning-xgboost-with-codes-python/
model_xgb=XGBClassifier()

prams={
    'learning_rate':[0.01,0.03,0.05,0.1,0.15,0.2],
     'n_estimators':[100,200,500,1000,2000],
     'max_depth':[3,5,10],
    'min_child_weight':[1,4,7],
    'colsample_bytree':[0.1,0.3,0.5,1],
    'subsample':[0.1,0.3,0.5,1]
}
model_xgb=RandomizedSearchCV(model_xgb,param_distributions=prams,verbose=10,n_jobs=-1,cv=5)
model_xgb.fit(x_train,y_train)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    3.6s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    6.2s
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   17.1s
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   18.8s
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   22.3s
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   27.7s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:   46.0s finished


[00:14:35] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, gamma=None,
                                           gpu_id=None, importance_type='gain',
                                           interaction_constraints=None,
                                           learning_rate=None,
                                           max_delta_step=None, max_depth=None,
                                           min_child_weight=None, missing=nan,
                                           monotone_constraints=None,
                                           n_estimators=100,...
                                           reg_lambda=None,
                                           scale_pos_weight=None,
                                           subsample=No

In [28]:
print(model_xgb.best_params_)

{'subsample': 0.5, 'n_estimators': 2000, 'min_child_weight': 1, 'max_depth': 10, 'learning_rate': 0.05, 'colsample_bytree': 0.3}


In [29]:
model_xgb =XGBClassifier(subsample=1,n_estimators=200,min_child_weight=1,max_depth=5,learning_rate=0.1,colsample_bytree=0.5)
model_xgb.fit(x_train,y_train)

[00:14:40] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.5, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.1, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=200, n_jobs=4, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [30]:
y_predict_xgb = model_xgb.predict(x_test)
score_xgb = model_xgb.score(x_test, y_test)
print(score_xgb)
print(metrics.classification_report(y_test, y_predict_xgb))

0.7448471926083866
              precision    recall  f1-score   support

           0       0.88      0.75      0.81      1015
           1       0.53      0.72      0.61       392

    accuracy                           0.74      1407
   macro avg       0.70      0.74      0.71      1407
weighted avg       0.78      0.74      0.75      1407



In [31]:
print(metrics.confusion_matrix(y_test, y_predict_xgb))

[[764 251]
 [108 284]]


In [32]:
f1_score(y_test, y_predict_xgb, average='macro')

0.7112400807432218

### AdaBoost classifier

In [33]:
model_adaboost=AdaBoostClassifier()

parameters={
    'learning_rate':[0.01,0.03,0.05],
     'n_estimators':[100,200,500]
}
model_adaboost=RandomizedSearchCV(model_adaboost,param_distributions=parameters,verbose=10,n_jobs=-1,cv=5)
model_adaboost.fit(x_train,y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    2.1s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    4.4s
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    7.9s
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   10.7s
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   15.5s
[Parallel(n_jobs=-1)]: Done  43 out of  45 | elapsed:   20.8s remaining:    0.9s
[Parallel(n_jobs=-1)]: Done  45 out of  45 | elapsed:   24.3s finished


RandomizedSearchCV(cv=5, estimator=AdaBoostClassifier(), n_jobs=-1,
                   param_distributions={'learning_rate': [0.01, 0.03, 0.05],
                                        'n_estimators': [100, 200, 500]},
                   verbose=10)

In [34]:
print(model_adaboost.best_params_)

{'n_estimators': 500, 'learning_rate': 0.05}


In [35]:
model_adaboost=AdaBoostClassifier(learning_rate=0.05,n_estimators=500)
model_adaboost.fit(x_train,y_train)

AdaBoostClassifier(learning_rate=0.05, n_estimators=500)

In [36]:
y_predict_ada = model_adaboost.predict(x_test)
score_ada= model_adaboost.score(x_test, y_test)
print(score_ada)
print(metrics.classification_report(y_test, y_predict_ada))

0.728500355366027
              precision    recall  f1-score   support

           0       0.90      0.70      0.79      1015
           1       0.51      0.80      0.62       392

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.74      1407



In [37]:
print(metrics.confusion_matrix(y_test, y_predict_ada))

[[712 303]
 [ 79 313]]


In [38]:
f1_score(y_test, y_predict_ada, average='macro')

0.7047572905131044

# Comparision Table

In [39]:
from prettytable import PrettyTable
print('Comparision between various Classification models')
X= PrettyTable(["Classifier Model","F1-score"]) 
X.add_row(["Logistic Regression", "58"]) 
X.add_row(["Decision Tree Classifier", "70"])
X.add_row(["Random Forest Classifier", "72"]) 
X.add_row(["Xgboost Classifier", "73"])
X.add_row(["Adaboost Classifier", "73"])
print(X)

Comparision between various Classification models
+--------------------------+----------+
|     Classifier Model     | F1-score |
+--------------------------+----------+
|   Logistic Regression    |    58    |
| Decision Tree Classifier |    70    |
| Random Forest Classifier |    72    |
|    Xgboost Classifier    |    73    |
|   Adaboost Classifier    |    73    |
+--------------------------+----------+


# Applying Models with Auto Encoders

In [40]:
num_of_inputs1=50
encoder1= Input(shape=(num_of_inputs1,))
encoding1 = Dense(32)(encoder1)
encoding1 = BatchNormalization()(encoding1)
encoding1 = LeakyReLU()(encoding1)
# encoder level 2
encoding1 = Dense(16)(encoding1)
encoding1 = BatchNormalization()(encoding1)
encoding1 = LeakyReLU()(encoding1)
# bottleneck
n_bottleneck_features1 =8
bottleneck_features1 = Dense(n_bottleneck_features1)(encoding1)

In [41]:
# define decoder, level 1
decoding1 = Dense(8)(bottleneck_features1)
decoding1 = BatchNormalization()(decoding1)
decoding1 = LeakyReLU()(decoding1)
# decoder level 2
decoding1  = Dense(16)(decoding1)
decoding1 = BatchNormalization()(decoding1)
decoding1  = LeakyReLU()(decoding1)
# output layer
decoding1 = Dense(32)(decoding1)
Decoder1=Dense(50,activation='linear')(decoding1)


In [42]:
# define autoencoder model
model = Model(inputs=encoder1, outputs=Decoder1)

In [43]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 50)]              0         
_________________________________________________________________
dense (Dense)                (None, 32)                1632      
_________________________________________________________________
batch_normalization (BatchNo (None, 32)                128       
_________________________________________________________________
leaky_re_lu (LeakyReLU)      (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_1 (Batch (None, 16)                64        
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 16)                0     

In [44]:
model.compile(loss='mse',optimizer='Adam',)

In [45]:
# fit the autoencoder model to reconstruct input
Auto_E_D1 = model.fit(x_train, y_train, epochs=50, batch_size=16, verbose=1, validation_data=(x_test, y_test))

Epoch 1/50
291/291 [==============================] - 2s 5ms/step - loss: 0.1685 - val_loss: 0.2197
Epoch 2/50
291/291 [==============================] - 1s 4ms/step - loss: 0.0906 - val_loss: 0.2533
Epoch 3/50
291/291 [==============================] - 1s 4ms/step - loss: 0.0882 - val_loss: 0.2249
Epoch 4/50
291/291 [==============================] - 1s 4ms/step - loss: 0.0777 - val_loss: 0.1632
Epoch 5/50
291/291 [==============================] - 1s 4ms/step - loss: 0.0765 - val_loss: 0.2018
Epoch 6/50
291/291 [==============================] - 1s 4ms/step - loss: 0.0800 - val_loss: 0.2683
Epoch 7/50
291/291 [==============================] - 1s 4ms/step - loss: 0.0726 - val_loss: 0.1800
Epoch 8/50
291/291 [==============================] - 1s 3ms/step - loss: 0.0694 - val_loss: 0.4063
Epoch 9/50
291/291 [==============================] - 1s 4ms/step - loss: 0.0712 - val_loss: 0.5757
Epoch 10/50
291/291 [==============================] - 1s 4ms/step - loss: 0.0693 - val_loss: 0.2123

In [46]:
encoder_only = Model(inputs=encoder1, outputs=bottleneck_features1 )

In [47]:
encoder_only.save('encoder_final.h5')

In [48]:
encoder_only = load_model('encoder_final.h5')

In [49]:
X_train_encoder = encoder_only.predict(x_train)

In [50]:
X_test_encoder = encoder_only.predict(x_test)

# Now Applying models with Auto encoders

### Logistic Regression with Sgdclassifier

In [51]:
model_lg_enc = SGDClassifier(alpha=0.01,loss='log',penalty='l2',random_state=24)
model_lg_enc.fit(X_train_encoder,y_train)

SGDClassifier(alpha=0.01, loss='log', random_state=24)

In [52]:
y_predict_lg_enc = model_lg_enc.predict(X_test_encoder)
score_enc = model_lg_enc.score(X_test_encoder, y_test)
print(score_enc)
print(metrics.classification_report(y_test, y_predict_lg_enc))
print(metrics.confusion_matrix(y_test, y_predict_lg_enc))

0.7370291400142146
              precision    recall  f1-score   support

           0       0.85      0.78      0.81      1015
           1       0.52      0.64      0.57       392

    accuracy                           0.74      1407
   macro avg       0.69      0.71      0.69      1407
weighted avg       0.76      0.74      0.74      1407

[[787 228]
 [142 250]]


In [53]:
f1_score(y_test, y_predict_lg_enc, average='macro')

0.6921917127855826

### Decision Tree Classifier

In [54]:
DT_enc = DecisionTreeClassifier()
max_depth=[1,5,10,50]
min_samples_split=[5,10,100,500]
parameters = {'max_depth':max_depth,'min_samples_split':min_samples_split}
clf_dt_enc = RandomizedSearchCV(DT_enc, parameters, cv= 10,return_train_score=True,verbose=2)
clf_dt_enc.fit(X_train_encoder, y_train)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
[CV] min_samples_split=5, max_depth=10 ...............................
[CV] ................ min_samples_split=5, max_depth=10, total=   0.0s
[CV] min_samples_split=5, max_depth=10 ...............................
[CV] ................ min_samples_split=5, max_depth=10, total=   0.1s
[CV] min_samples_split=5, max_depth=10 ...............................
[CV] ................ min_samples_split=5, max_depth=10, total=   0.1s
[CV] min_samples_split=5, max_depth=10 ...............................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] ................ min_samples_split=5, max_depth=10, total=   0.0s
[CV] min_samples_split=5, max_depth=10 ...............................
[CV] ................ min_samples_split=5, max_depth=10, total=   0.1s
[CV] min_samples_split=5, max_depth=10 ...............................
[CV] ................ min_samples_split=5, max_depth=10, total=   0.0s
[CV] min_samples_split=5, max_depth=10 ...............................
[CV] ................ min_samples_split=5, max_depth=10, total=   0.0s
[CV] min_samples_split=5, max_depth=10 ...............................
[CV] ................ min_samples_split=5, max_depth=10, total=   0.1s
[CV] min_samples_split=5, max_depth=10 ...............................
[CV] ................ min_samples_split=5, max_depth=10, total=   0.1s
[CV] min_samples_split=5, max_depth=10 ...............................
[CV] ................ min_samples_split=5, max_depth=10, total=   0.0s
[CV] min_samples_split=10, max_depth=10 ..............................
[CV] .

[CV] ................ min_samples_split=10, max_depth=1, total=   0.0s
[CV] min_samples_split=10, max_depth=1 ...............................
[CV] ................ min_samples_split=10, max_depth=1, total=   0.0s
[CV] min_samples_split=10, max_depth=1 ...............................
[CV] ................ min_samples_split=10, max_depth=1, total=   0.0s
[CV] min_samples_split=10, max_depth=1 ...............................
[CV] ................ min_samples_split=10, max_depth=1, total=   0.0s
[CV] min_samples_split=10, max_depth=1 ...............................
[CV] ................ min_samples_split=10, max_depth=1, total=   0.0s
[CV] min_samples_split=10, max_depth=1 ...............................
[CV] ................ min_samples_split=10, max_depth=1, total=   0.0s
[CV] min_samples_split=10, max_depth=1 ...............................
[CV] ................ min_samples_split=10, max_depth=1, total=   0.0s
[CV] min_samples_split=10, max_depth=1 ...............................
[CV] .

[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    3.6s finished


RandomizedSearchCV(cv=10, estimator=DecisionTreeClassifier(),
                   param_distributions={'max_depth': [1, 5, 10, 50],
                                        'min_samples_split': [5, 10, 100, 500]},
                   return_train_score=True, verbose=2)

In [55]:
print(clf_dt_enc.best_estimator_)

DecisionTreeClassifier(max_depth=5, min_samples_split=5)


In [56]:
clf_enc=DecisionTreeClassifier(max_depth=5, min_samples_split=5)
clf_enc.fit(X_train_encoder,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_split=5)

In [57]:
y_predict_dt_enc = clf_enc.predict(X_test_encoder)
score_dt = clf_enc.score(X_test_encoder, y_test)
print(score_dt)
print(metrics.classification_report(y_test, y_predict_dt_enc))

0.736318407960199
              precision    recall  f1-score   support

           0       0.86      0.76      0.81      1015
           1       0.52      0.69      0.59       392

    accuracy                           0.74      1407
   macro avg       0.69      0.72      0.70      1407
weighted avg       0.77      0.74      0.75      1407



In [58]:
print(metrics.confusion_matrix(y_test, y_predict_dt_enc))

[[767 248]
 [123 269]]


In [59]:
f1_score(y_test, y_predict_dt_enc, average='macro')

0.6985542648753064

### Random Forest Classifier

In [60]:
from scipy.stats import randint as sp_randint
param_dist = {'n_estimators':[100,200,500,1000,2000],
              'max_depth':[3,5,10],
              "min_samples_split": sp_randint(10,19),
              "min_samples_leaf": sp_randint(25,65)}

clf_enc = RandomForestClassifier(random_state=25,n_jobs=-1)

rf_random_enc = RandomizedSearchCV(clf_enc, param_distributions=param_dist,
                                   n_iter=5,cv=5,random_state=25,return_train_score=True)

rf_random_enc.fit(X_train_encoder,y_train)

RandomizedSearchCV(cv=5,
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=25),
                   n_iter=5,
                   param_distributions={'max_depth': [3, 5, 10],
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000015AF73747F0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000015AF73875E0>,
                                        'n_estimators': [100, 200, 500, 1000,
                                                         2000]},
                   random_state=25, return_train_score=True)

In [61]:
print(rf_random_enc.best_estimator_)

RandomForestClassifier(max_depth=10, min_samples_leaf=33, min_samples_split=14,
                       n_estimators=200, n_jobs=-1, random_state=25)


In [62]:
clf_rf_enc = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=33, min_samples_split=14,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
            oob_score=False, random_state=25, verbose=0, warm_start=False)

In [63]:
clf_rf_enc.fit(X_train_encoder,y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=33, min_samples_split=14,
                       n_estimators=200, n_jobs=-1, random_state=25)

In [64]:
y_predict_rf_enc = clf_rf_enc.predict(X_test_encoder)
score_rf_enc = clf_rf_enc.score(X_test_encoder, y_test)
print(score_rf_enc)
print(metrics.classification_report(y_test, y_predict_rf_enc))


0.7391613361762616
              precision    recall  f1-score   support

           0       0.88      0.74      0.80      1015
           1       0.52      0.73      0.61       392

    accuracy                           0.74      1407
   macro avg       0.70      0.74      0.71      1407
weighted avg       0.78      0.74      0.75      1407



In [65]:
print(metrics.confusion_matrix(y_test, y_predict_rf_enc))

[[753 262]
 [105 287]]


In [66]:
f1_score(y_test, y_predict_rf_enc, average='macro')

0.7070235172565225

### XGBoost Classifier

In [67]:
# https://www.analyticsvidhya.com/blog/2016/03/complete-guide-parameter-tuning-xgboost-with-codes-python/
model_xgb_enc=XGBClassifier()

prams={
    'learning_rate':[0.01,0.03,0.05,0.1,0.15,0.2],
     'n_estimators':[100,200,500,1000,2000],
     'max_depth':[3,5,10],
    'min_child_weight':[1,4,7],
    'colsample_bytree':[0.1,0.3,0.5,1],
    'subsample':[0.1,0.3,0.5,1]
}
model_xgb_enc=RandomizedSearchCV(model_xgb_enc,param_distributions=prams,verbose=10,n_jobs=-1,cv=5)
model_xgb_enc.fit(X_train_encoder,y_train)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    1.6s
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    6.7s
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   12.3s
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   15.9s
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   20.9s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:   28.9s finished


[00:18:02] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, gamma=None,
                                           gpu_id=None, importance_type='gain',
                                           interaction_constraints=None,
                                           learning_rate=None,
                                           max_delta_step=None, max_depth=None,
                                           min_child_weight=None, missing=nan,
                                           monotone_constraints=None,
                                           n_estimators=100,...
                                           reg_lambda=None,
                                           scale_pos_weight=None,
                                           subsample=No

In [68]:
print(model_xgb_enc.best_params_)

{'subsample': 1, 'n_estimators': 100, 'min_child_weight': 4, 'max_depth': 10, 'learning_rate': 0.01, 'colsample_bytree': 0.3}


In [69]:
model_xgb_enc =XGBClassifier(subsample=0.5,n_estimators=2000,min_child_weight=1,max_depth=3,learning_rate=0.01,colsample_bytree=1)
model_xgb_enc.fit(X_train_encoder,y_train)

[00:18:02] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.01, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=2000, n_jobs=4, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=0.5,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [70]:
y_predict_xgb_enc = model_xgb_enc.predict(X_test_encoder)
score_xgb_enc = model_xgb_enc.score(X_test_encoder, y_test)
print(score_xgb_enc)
print(metrics.classification_report(y_test, y_predict_xgb_enc))

0.738450604122246
              precision    recall  f1-score   support

           0       0.87      0.75      0.81      1015
           1       0.52      0.71      0.60       392

    accuracy                           0.74      1407
   macro avg       0.70      0.73      0.70      1407
weighted avg       0.77      0.74      0.75      1407



In [71]:
print(metrics.confusion_matrix(y_test, y_predict_xgb_enc))
f1_score(y_test, y_predict_xgb_enc, average='macro')

[[760 255]
 [113 279]]


0.7038382692096496

### AdaBoost Classifier

In [72]:
model_adaboost_enc=AdaBoostClassifier()

parameters={
    'learning_rate':[0.01,0.03,0.05],
     'n_estimators':[100,200,500]
}
model_adaboost_enc=RandomizedSearchCV(model_adaboost_enc,param_distributions=parameters,verbose=10,n_jobs=-1,cv=5)
model_adaboost_enc.fit(X_train_encoder,y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    1.2s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    3.1s
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    6.0s
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    8.4s
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   12.5s
[Parallel(n_jobs=-1)]: Done  43 out of  45 | elapsed:   17.5s remaining:    0.7s
[Parallel(n_jobs=-1)]: Done  45 out of  45 | elapsed:   21.4s finished


RandomizedSearchCV(cv=5, estimator=AdaBoostClassifier(), n_jobs=-1,
                   param_distributions={'learning_rate': [0.01, 0.03, 0.05],
                                        'n_estimators': [100, 200, 500]},
                   verbose=10)

In [73]:
print(model_adaboost_enc.best_params_)

{'n_estimators': 200, 'learning_rate': 0.03}


In [74]:
model_adaboost_enc=AdaBoostClassifier(learning_rate=0.05,n_estimators=500)
model_adaboost_enc.fit(X_train_encoder,y_train)

AdaBoostClassifier(learning_rate=0.05, n_estimators=500)

In [75]:
y_predict_ada_enc = model_adaboost_enc.predict(X_test_encoder)
score_ada_enc= model_adaboost_enc.score(X_test_encoder, y_test)
print(score_ada_enc)
print(metrics.classification_report(y_test, y_predict_ada_enc))

0.7412935323383084
              precision    recall  f1-score   support

           0       0.87      0.76      0.81      1015
           1       0.53      0.69      0.60       392

    accuracy                           0.74      1407
   macro avg       0.70      0.73      0.70      1407
weighted avg       0.77      0.74      0.75      1407



In [76]:
print(metrics.confusion_matrix(y_test, y_predict_ada_enc))
f1_score(y_test, y_predict_ada_enc, average='macro')

[[771 244]
 [120 272]]


0.7040715385219871

### Comparision Table for MOdels with Auto encoders

In [77]:
from prettytable import PrettyTable
print('Comparision between various Classification models with auto encoders')
X= PrettyTable(["Classifier Model","F1-score"]) 
X.add_row(["Logistic Regression", "73"]) 
X.add_row(["Decision Tree Classifier", "74"])
X.add_row(["Random Forest Classifier", "74"]) 
X.add_row(["Xgboost Classifier", "75"])
X.add_row(["Adaboost Classifier", "74"])
print(X)

Comparision between various Classification models with auto encoders
+--------------------------+----------+
|     Classifier Model     | F1-score |
+--------------------------+----------+
|   Logistic Regression    |    73    |
| Decision Tree Classifier |    74    |
| Random Forest Classifier |    74    |
|    Xgboost Classifier    |    75    |
|   Adaboost Classifier    |    74    |
+--------------------------+----------+


### Comparision Table between various models with and without auto aencoders

In [78]:
from prettytable import PrettyTable
print('Comparision between various Classification models with auto encoders')
X= PrettyTable(["Classifier Model","F1-score without encoders","F1-score with encoders"]) 
X.add_row(["Logistic Regression", "58","73"]) 
X.add_row(["Decision Tree Classifier", "70","74"])
X.add_row(["Random Forest Classifier", "72","74"]) 
X.add_row(["Xgboost Classifier", "73","75"])
X.add_row(["Adaboost Classifier", "73","74"])
print(X)

Comparision between various Classification models with auto encoders
+--------------------------+---------------------------+------------------------+
|     Classifier Model     | F1-score without encoders | F1-score with encoders |
+--------------------------+---------------------------+------------------------+
|   Logistic Regression    |             58            |           73           |
| Decision Tree Classifier |             70            |           74           |
| Random Forest Classifier |             72            |           74           |
|    Xgboost Classifier    |             73            |           75           |
|   Adaboost Classifier    |             73            |           74           |
+--------------------------+---------------------------+------------------------+


# Saving model XGBoost of auto encoders

In [93]:

import pickle
# open a file, where you ant to store the data
file = open('flight_rf.pkl', 'wb')

# dump information to that file
pickle.dump(model_xgb, file)

In [86]:
final_file = 'final_xg_boost.pkl'

In [87]:
pickle.dump(model_xgb, open(final_file, 'wb'))

In [88]:
model = pickle.load(open(final_file, 'rb'))

In [91]:
score_model = model.score(x_test, y_test)

In [92]:
score_model

0.7448471926083866